name: conduit
version: 2.0.0-b6
homepage: https://github.com/conduit-dart/conduit
description: A modern HTTP server application framework, ORM and OAuth2 provider with OpenAPI 3.0 integration. Foundation for REST, RPC or GraphQL services.
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  args: ^2.0.0
  analyzer: ^1.3.0
  collection: ^1.15.0
  conduit_common: ^1.0.0
  conduit_config: ^1.0.0-0
  conduit_isolate_exec: ^1.0.0-0
  conduit_open_api: ^1.0.0-0
  conduit_password_hash: ^1.0.0-0
  conduit_runtime: ^1.0.0-0
  crypto: ^3.0.0
  logging: ^1.0.0
  meta: ^1.1.5
  path: ^1.6.1
  postgres: ^2.3.1
  pub_cache: ^0.3.0
  pub_semver: ^2.0.0
  yaml: ^3.1.0
dev_dependencies:
  conduit_common_test:
    path: ../common_test
  conduit_test:
    path: ../test_harness
  dcli: ^1.3.0
  fs_test_agent: ^1.0.0-0
  http: ^0.13.0
  matcher: ">=0.12.3 <0.14.0"
  mockito: ^5.0.0
  pedantic: ^1.0.0
  settings_yaml: ^3.0.3
  test: ^1.16.5

# dependency_overrides:
#   conduit_common:
#     path: ../common
#   conduit_config: 
#     path: ../config
#   conduit_isolate_exec:
#     path: ../isolate_exec
#   conduit_open_api: 
#     path: ../open_api
#   conduit_password_hash:
#     path: ../password_hash
#   conduit_runtime: 
#     path: ../runtime
#   fs_test_agent:
#     path: ../fs_test_agent

executables:
  conduit: conduit
