name: conduit_test
author: stable|kernel <jobs@stablekernel.com>
version: 2.0.0-a3
homepage: https://github.com/conduit-dart/conduit
description: Utilities for writing automated tests for Conduit applications
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  test: ^1.3.0
  matcher: '>=0.12.3 <0.14.0'
  conduit: ^2.0.0-0
  conduit_common_test: ^2.0.0-0
