name: Conduit
repository: https://github.com/conduit-dart/conduit
packages:
  - packages/**
ignore:
  - ci
  - wildfire
command:
  version:
    linkToCommits: true
scripts:
  analyze: melos exec -- pub global run tuneup check
  hello_flutter:
    run: melos exec -- "echo 'Hello $(dirname $PWD)'"
environment:
  sdk: ">=2.12.0 <3.0.0"
  