name: conduit_runtime
version: 2.0.0-b6
description: Provides behaviors and base types for packages that can use mirrors and be AOT compiled.
repository: https://github.com/conduit-dart/conduit-runtime
environment: 
  sdk: '>=2.12.0-0 <3.0.0'
dependencies: 
  analyzer: ^1.2.0
  args: ^2.0.0
  conduit_isolate_exec: ^2.0.0-b6
  path: ^1.8.0
  pubspec: ^2.0.1
  yaml: ^3.1.0
dev_dependencies: 
  dcli: ^1.5.0
  lint: ^1.5.0
  test: ^1.16.5
  fs_test_agent: 
    path: ../fs_test_agent

# So we can tests against the same version of
# every package we need to set path overrides.
# The overrides are fixed by the publish process
# when you run ci/bin/release.dart
# We need direct depdencies as well
# as transitive dependencies listed.    
dependency_overrides: 
  conduit_isolate_exec: 
    path: ../isolate_exec
