name: conduit_postgresql
description: The postgresql ORM for conduit.
version: 4.3.7
repository: https://github.com/conduit-dart/conduit

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  collection: ^1.17.1
  conduit_core: ^4.3.8
  postgres: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.6
