name: conduit_common
version: 2.0.0-b6
description: Common classes shared by conduit projects.
repository: https://github.com/bsutton/conduit-orm
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  conduit_open_api: ^2.0.0-b6
  dcli: ^1.0.0
dev_dependencies: 
  lint: ^1.0.0

# So we can tests against the same version of
# every package we need to set path overrides.
# The overrides are fixed by the publish process
# when you run ci/bin/release.dart
# We need direct depdencies as well
# as transitive dependencies listed.    
dependency_overrides:
  conduit_codable:
    path: ../codable
  conduit_open_api: 
    path: ../open_api

