name: conduit_ci
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dcli: ^1.5.0
  settings_yaml: ^3.0.0
  conduit_common_test: ^2.0.0-0

dev_dependencies:
  lint: ^1.0.0

dependencies_overrides:
  conduit_common_test:
    path: ../conduit_common_test
