name: conduit_ci
version: 2.0.0-b6
description: A simple command-line application.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  conduit_common: ^2.0.0-b6
  dcli: ^1.5.0
  settings_yaml: ^3.0.0
  conduit_common_test: ^2.0.0-b6
dev_dependencies: 
  lint: ^1.0.0
dependency_overrides: 
  conduit_common_test: 
    path: ../common_test
  conduit_common: 
    path: ../common
