name: conduit_open_api
version: 2.0.0-b6
homepage: https://github.com/conduit-dart/open-api-dart
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
environment: 
  sdk: '>=2.12.0-0 <3.0.0'
dependencies: 
  conduit_codable: ^2.0.0-b6
  meta: ^1.1.5
dev_dependencies: 
  dcli: ^1.5.1
  lint: ^1.5.3
  test: ^1.3.0


# So we can tests against the same version of
# every package we need to set path overrides.
# The overrides are fixed by the publish process
# when you run ci/bin/release.dart
# We need direct depdencies as well
# as transitive dependencies listed.
dependency_overrides:
  conduit_codable: 
    path: ../codable

